### ISSUE TITLE
Can't start a post with formatted text

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Editor-Android#298] opened 2016-02-25 01:53 UTC
The same issue in iOS (https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/754) applies to the android editor as well.
1. Start a brand new post
2. Tap in the content field
3. Tap the bold button on the keyboard
4. Start typing post content, and observe that the text is not bolded.

Galaxy S6, Android 5.1

**Comment by aforcier** [comment] 2016-02-25 01:55
Duplicate of https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/204, though adding the reference to track the iOS-side issue.

**Closed as completed by aforcier** 2016-02-25 01:55 UTC
Labels: [Type] Bug

**Comment by roundhill** [comment] 2016-02-25 01:58
Ah nice, sorry I skimmed the issues but missed that one I guess!

**Comment by aforcier** [comment] 2016-02-25 01:59
We do have a good amount of them... ;)
