### ISSUE TITLE
Editor: End tag can be set before starting tag. 

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#85] opened 2015-04-04 20:36 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/491

In the editor tap to edit the content. 

Somewhere in the middle of the content, tap one of the formatting options.  I chose bold. 
Notice the opening bold tag is set, and the bold option is highlighted.
Move the cursor to a point in the text prior to the opening bold tag. 
Tap the bold format option again to set the closing tag. 

We could argue that this is on the user, but if the cursor is moved prior to the start of the format tag it might make sense to reset the button's state.

**Comment by rachelmcr** [comment] 2016-03-22 18:18
This is not an issue in the visual editor, where tapping the bold button does not add a tag unless a word is highlighted (in which case opening and closing tags are set). The above steps still reproduce the issue in HTML mode, but if you switch back to visual mode, the closing tag is removed and a new closing tag is placed after the text.

This matches the behavior in the web interface in wp-admin. Since the issue doesn't exist in the visual editor and resolves itself gracefully in the HTML editor (in parity with the web interface) I'm going to close this issue.

Tested on Nexus 9, Android 6.0.1, alpha-4.

**Closed as completed by rachelmcr** 2016-03-22 18:18 UTC
Labels: old editor, old editor - reviewed
