### ISSUE TITLE
"Select from media library" shows default icons instead of image previews

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#50] opened 2015-04-04 20:28 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1508

Add images from the media library to a post, and you'll see default thumbnails instead of previews of the actual images:

![missing image icons](https://cloud.githubusercontent.com/assets/3476361/3291100/dc6dc4c2-f580-11e3-9032-b61f61f0519a.png)

**Comment by rachelmcr** [comment] 2016-03-14 16:17
I re-tested this issue in the visual editor and can't reproduce it. I tried with a self-hosted site, a public WordPress.com site, and a private WordPress.com site, and in each case the thumbnail images in the media library showed up as expected. Closing as resolved.

Tested with Nexus 9, Android 6.0.1, app v. alpha-3.

**Closed as completed by rachelmcr** 2016-03-14 16:17 UTC
Labels: old editor, old editor - reviewed
