### ISSUE TITLE
Samsung S3 image/video spacing issue

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#241] opened 2015-08-28 17:17 UTC
There is currently a bug occurring on the Samsung S3 (`API 18`). It ignores the space and you're stuck with the cursor on the left side of the image - no way to keep typing under the image without going into HTML mode. This didn't happen on emulators (`API 14-22`), but I trust physical devices more - we might need some testing on older devices to figure out the extent of the issue.

The S3 issue can be fixed by using a zero-width space character (`U+200B`) instead of `<br>` as a separator [here](https://github.com/wordpress-mobile/WordPress-Editor-Android/blob/ddb5454bd7a6a932eaf0bbb5ea0ddb531a16233b/libs/editor-common/assets/ZSSRichTextEditor.js#L834). This works on all devices, but messes up autocorrect - the ZW space character is treated as a real character, so the keyboard switches to lowercase under the image (as if a sentence had already started). There might be a different solution for the spacing that will work everywhere with no issues, or we might be able to force the autocapitalization back on after images.

ref: #236

**Comment by aforcier** [comment] 2016-01-19 20:46
Also experiencing the same issue with videos on the Samsung S3.

**Comment by aforcier** [comment] 2016-04-27 11:32
Can't reproduce this anymore, most likely fixed by the `p` -> `div` change.

**Closed as completed by aforcier** 2016-04-27 11:32 UTC
Labels: [Type] Bug, Samsung
