### ISSUE TITLE
Upload media error when uploading a new post is unclear

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#42] opened 2015-04-04 20:25 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1703

For instance, (no reference to the post or blog, technical details, not sure if the post has been uploaded without the media)
![screen shot 2014-08-02 at 10 12 17](https://cloud.githubusercontent.com/assets/40213/3787481/c599c8a2-1a1c-11e4-8503-26c58e34d53d.png)

Also we should be careful, and not show network layer or API errors to the user - errors should be the way to tell them what failed, and what they can do next.

**Comment by maxme** [comment] 2016-02-03 14:52
Visual editor only shows "Tap to try again" when the user fails to upload his media. 

We should probably adopt the same solution proposed in https://github.com/wordpress-mobile/WordPress-iOS/issues/4075

Also note that the current string "Tap to try again" can't be localized.

**Comment by aforcier** [comment] 2016-02-24 16:38
Duplicate of https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/286, which was merged in https://github.com/wordpress-mobile/WordPress-Android/pull/3770.

**Closed as completed** 2016-02-24 16:39 UTC
Labels: old editor, old editor - reviewed
