### ISSUE TITLE
Draft post coming from nowhere after post has been published

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#48] opened 2015-04-04 20:26 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1540

One user first noticed this behaviour of zombie draft posts. I noticed it, only after using the "Share picture with WordPress" feature a lot (but I'm not sure this is related).
- Publish post "A" via "Share with WordPress"
- Publish post "B" via "Share with WordPress"
- Publish post "..." via "Share with WordPress"
- Notice post "B" is published and a draft "B" is also there

**Comment by rachelmcr** [comment] 2016-03-24 17:45
I have been testing in the new editor and haven't been able to reproduce these zombie draft posts there (by sharing photos to WordPress or other means).

@maxme - since you opened the original issue for this, do you think we need to keep this issue open? I'm not sure if there's another way to still reproduce the issue, but I also can't recall any recent reports from users about this.

I tested on Nexus 9, Android 6.0.1, alpha-4.

**Comment by maxme** [comment] 2016-03-24 17:51
I'm closing it, will reopen if we can reproduce it or have another report.

**Closed as completed by maxme** 2016-03-24 17:51 UTC
Labels: old editor, old editor - reviewed
