### ISSUE TITLE
Creating Draft on Android App sets publish time to current time

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#79] opened 2015-04-04 20:36 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/684

Creating a draft on Android has a different behavior than on the Web interface.
When creating a draft, you leave the Publish: at Immediately and change the status to draft it will save the publish date (as current date/time) when you access the post in the web interface, the publish time will be the time the draft was created. Therefore when you press publish it gets published back in time.

This is a different behavior than the web interface where when saving a draft the Publish date stays to "Immediately" and then later on when you hit publish it sets to the current publish date and not the previous draft date.

**Comment by rachelmcr** [comment] 2016-03-21 19:05
I tested and couldn't reproduce this issue in the new editor.

When a draft is saved in the app, it displays the date/time the draft was saved. However, if you publish that draft at a later time, the draft is published with the current date/time (not the saved draft date/time). In the web interface, a draft that was saved in the app appears with "Publish immediately" as its publish date, and is published immediately.

That said, the current behavior can cause trouble if you intentionally backdated a draft and _want_ to publish it with that date/time. I'd recommend having a "Publish Immediately" option for the publish date. See a similar discussion for iOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/3516

Nexus 9, Android 6.0.1, alpha-4.

**Comment by rachelmcr** [comment] 2016-04-14 15:41
Closing this issue as it isn't related to the visual editor. The issue with the draft's publish date/time is related to the XMLRPC API and is being tracked in the main repo: https://github.com/wordpress-mobile/WordPress-Android/issues/3913

**Closed as completed by rachelmcr** 2016-04-14 15:41 UTC
Labels: old editor, old editor - reviewed
