### ISSUE TITLE
Media edits are lost after hitting back button

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#95] opened 2015-04-04 20:38 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/224

If you open a media item for editing then make any changes, those changes are lost without warning when you hit the back button.

**Comment by aforcier** [comment] 2015-10-28 18:02
Now a duplicate of #261.

**Closed as completed** 2015-10-28 18:02 UTC
Labels: old editor
