### ISSUE TITLE
First character inserted appears as zw space

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-Android#230] opened 2015-08-18 15:28 UTC
repro
- on a nifty kitkat samsung device, tap create post
- type title
- insert caret in body
- tap any letter
- see zero width whitespace inserted instead of capital letter

![](https://cloudup.com/ijIKp9Y90ac+)

**Comment by aforcier** [comment] 2015-08-23 17:19
I'm able to reproduce this on an `API 19` (Kit Kat) emulator too:

https://cloudup.com/cglu27gsbiT

It's also happening on an `API 21` emulator, but not `API 22` (emulator or devices). This is possibly another Chromium bug. If it is, the bug was introduced no later than Chromium 30 (the version running on Android `4.4.2`, @meremagee's device's Android version), and fixed no earlier than Chromium 38:

4.3: Android WebKit (no bug)
4.4.2: Chromium `30` (bug)
4.4.4: Chromium `37` (bug)
5.0 (emulator): Chromium `37` (bug)
5.1 (emulator): Chromium `39` (no bug)

If that's indeed what's happening, we don't need to worry too much about `5.0` (`API 21`) devices, as the WebView is updated independently. Still a problem on Kit Kat though.

Given this, I'm dropping the Samsung tag and tagging the specific versions affected.

**Comment by rachelmcr** [comment] 2016-03-28 19:17
This was reported by Grace in alpha testing on her Galaxy Samsung S4:

> Whenever I create a new post in the editor underneath the title the first letter that I touch ends up being `​&#x200b;`. No matter what letter I touch, it turns to that. But if I keep typing it disappears but I still miss the first letter.

**Comment by maxme** [comment] 2016-04-06 16:46
With a hardware keyboard on a Sony Z5C, android 6.0:
1. Open the editor, type `TAB` to give the focus to the content, type `TAB` again, see the ZW char `&#x200b` in content
2. Open the editor, type `TAB` twice (get a `&#x200b`), focus is given to the button bar but when you type, it adds char to the content field (like the content field had focus). This is weird because the cursor is invisible, and there is no visual feedback about current focus.

**Comment by aforcier** [comment] 2016-04-15 18:55
Opened a separate issue for the tab format bar focus issue, https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/355. The rest of this issue is being addressed in #354.

**Closed as completed** 2016-04-19 12:30 UTC
Labels: [Type] Bug, API19, API21
