### ISSUE TITLE
Inserting big images can break the width of certain themes

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#39] opened 2015-04-04 20:25 UTC
Original issue: https://github.com/wordpress-mobile/WordPress-Android/issues/1879

From one of our user:

> When using the web-based interface, if an image is inserted too large for a theme's width, the largest version possible for the theme is displayed. Something about how the image is inserted using the app makes this value absolute for the image and breaks the width of a few templates I have tested with on .org (twenty-fourteen and interface at least).﻿

**Comment by rachelmcr** [comment] 2016-03-14 16:04
I can reproduce this in the legacy editor, but as of alpha-3 I can't reproduce it in the new visual editor. Here are the steps I used:
1. Disable the visual editor (to test in the legacy editor)
2. Select a self-hosted site using the Twenty Fourteen theme
3. Open editor to start a new post
4. Add a post title
5. Select a large image (wider than the theme's width) and add it to the post
6. Publish the post

Result: The image added in the legacy editor was inserted at its full width, wider than the theme's width.

I then repeated the same steps, using the same image, in the visual editor. When using the visual editor, I couldn't reproduce the issue. Closing as resolved in the new editor.

Tested with Nexus 9, Android 6.0.1, app v. alpha-3.

**Closed as completed by rachelmcr** 2016-03-14 16:04 UTC
Labels: old editor, old editor - reviewed
