### ISSUE TITLE
Blockquote command is reverted on autocorrected words (API 22)

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-Android#159] opened 2015-06-10 02:43 UTC
Originally noted here: #153 by @aforcier:

> Ran into some weirdness on an API22 Nexus 4:
> 
> https://cloudup.com/cN0k8O4nIXV
> 
> This seems to be another autocorrect-related issue - disabling autocorrect got rid of this bug. Haven't had any other issues yet (everything seems to work great with autocorrect off anyway). I'll test this on an API18 Galaxy S3 next week.

This issue does not occur on API 21 (and lower) devices. Only API 22 seems to be affected (unable to confirm on Samsung because the S6 does not have API 22 upgrade yet)

Inspecting the device after the error occurs shows the blockquote node is being turned into a span:

![screen shot 2015-06-09 at 8 40 11 pm](https://cloud.githubusercontent.com/assets/154014/8073229/eae3631e-0ee7-11e5-87f5-e888e231caad.png)

Pressing the blockquote button again re-applies the blockquote correctly.

**Comment by aforcier** [comment] 2015-06-10 13:15
Confirming that I can't reproduce this on API 21 and down emulators. Also, FWIW, the issue is still present on a Nexus 9 running the current Android M developer preview.

**Comment by aforcier** [comment] 2016-04-21 14:52
Can't reproduce this anymore on API22, device (Nexus 4) or emulator. Looks like it was fixed by the `p`>`div` switch.

**Closed as completed** 2016-04-21 14:52 UTC
Labels: [Type] Bug, API22
